# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.3'

gem 'pg'
gem 'bootsnap', require: false
gem 'bootstrap3-rails'
gem 'chartkick'
gem 'connection_pool'
gem 'devise'
gem 'figaro'
gem 'friendly_id'
gem 'geocoder'
gem 'haml'
gem 'image_processing', '~> 1.2'
gem 'importmap-rails'
gem 'interactor'
gem 'jbuilder'
gem 'jquery-rails'
gem 'kaminari'
gem 'kaminari-bootstrap3'
gem 'mapkick'
gem 'omniauth-github'
gem 'puma', '~> 5.0'
gem 'pundit'
gem 'rails', '~> 7.0.8'
gem 'ransack', '~> 3.2.1'
gem 'redis'
gem 'rolify'
gem 'sassc'
gem 'simple_form'
gem 'social-share-button'
gem 'sprockets-rails'
gem 'sqlite3', '~> 1.4'
gem 'tzinfo-data', platforms: %i[ mingw mswin x64_mingw jruby ]
gem 'view_component'
gem 'wicked'

group :development do
  gem 'annotate'
  gem 'binding_of_caller'
  gem 'awesome_print'
  gem 'better_errors'
  gem 'brakeman'
  gem 'bullet'
  gem 'dotenv-rails'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'fasterer'
  gem 'ffaker'
  gem 'flog'
  gem 'overcommit'
  gem 'rails-erd'
  gem 'rspec-rails'
  gem 'rubocop'
  gem 'rubocop-rspec'
  gem 'rubycritic'
  gem 'shoulda'
  gem 'web-console'
end

