name: Rails CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 3.2.0

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Database setup
      run: |
        bundle exec rake db:create
        bundle exec rake db:migrate

    - name: Run tests
      run: bundle exec rspec

    - name: Deploy to production
      if: success()
      run: |

    - name: Notify on failure
      if: failure()
      run: |
